<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Про нас',
    'Contacts' => 'Контакти',
    'Home' => 'Головна',
    'Book' => 'Книги',
    'My Company' => 'Read It',
    'online library' => 'онлайн-бібліотека',
    'Log in' => 'Вхід',
    'Log out' => 'Вихід',
    'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' =>
        'Якщо у вас є ділова пропозиція або інші питання, будь ласка, заповніть наступну форму, щоб зв\'язатися з нами. Дякуємо!',
    'Are you sure you want to delete this item?' => 'Ви впевнені, що хочете видалити цей пункт?',
    'Author' => 'Автори',
    'Books' => 'Книги',
    'Create' => 'Створити',
    'Create Book' => 'Додати книгу',
    'Delete' => 'Видалити',
    'Description' => 'Опис',
    'ID' => 'ID',
    'Reset' => 'Скинути',
    'Search' => 'Пошук',
    'Title' => 'Назва',
    'Update' => 'Редагувати',
    'Update {modelClass}: ' => 'Редагувати {modelClass}: ',
];
