<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Despre',
    'Contacts' => 'Contacte',
    'Home' => 'Acasă',
    'Book' => 'Carte',
    'My Company' => 'Read It',
    'online library' => 'bibliotecă on-line',
    'Log in' => 'Log in',
    'Log out' => 'Log out',
    'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' =>
        'Dacă aveți întrebări de afaceri sau alte întrebări, vă rugăm să completați formularul de mai jos pentru a ne contacta. Multumesc!',
    'Are you sure you want to delete this item?' => 'Sigur doriți să ștergeți acest element?',
    'Author' => 'Autorul',
    'Books' => 'Cărți',
    'Create' => 'Creați',
    'Create Book' => 'Crearea de carte',
    'Delete' => 'Delete',
    'Description' => 'Descriere',
    'ID' => 'ID',
    'Reset' => 'Reset',
    'Search' => 'Cautare',
    'Title' => 'Titlu',
    'Update' => 'Actualizare',
    'Update {modelClass}: ' => 'Actualizare {modelClass}:',
];
